apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
  labels:
    app: web-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web-dep
      labels:
        app: web
    spec:
      containers:
        - name: web-dep
          image: forzalino/web:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
      restartPolicy: Always
      